name: Dispatch CI

on:
  # At 2:00 PM UTC, only on Tuesday, Wednesday and Thursday
  schedule:
    - cron: '0 14 * * 2,3,4'
  workflow_dispatch:
    inputs:
      major_type:
        description: 'Major branch type'
        required: true
        type: choice
        options:
          - current
          - previous
      minor_type:
        description: 'Minor branch type'
        required: true
        type: choice
        options:
          - next-patch
          - next-minor    

jobs:
  dispatch-ci:
    name: Dispatch CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch CI
        uses: emteknetnz/gha-dispatch-ci@main
